#!/bin/bash
apt-get update && apt-get install -y nodejs
if ! [ -L /usr/bin/node ]; then
  ln -fs /usr/bin/nodejs /usr/bin/node
fi
apt-get install -y npm
chown -R $(whoami) /usr/local
npm install -g npm
pgrep node | xargs kill
